import Link from "next/link";
import { getOrganizationContext } from "@/lib/supabase/auth-context";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { getValueCase } from "@/lib/value/value-case-repository";
import { ProjectActions } from "./ProjectActions";

export default async function ConsultantProjectDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const context = await getOrganizationContext();
  const supabase = await createSupabaseServerClient();
  const result = await supabase.from<Record<string, unknown>>("consulting_projects").select("id, organization_id, opportunity_id, name, status, start_date, target_end_date, completed_at, contract_value, currency, created_at, updated_at").eq("id", id).eq("organization_id", context.organizationId).maybeSingle();
  if (result.error || !result.data) return <main className="min-h-screen bg-slate-50 p-8 text-slate-950"><Link href="/consultant/projects" className="text-sm text-sky-700">← Projects</Link><h1 className="mt-6 text-3xl font-semibold">Project not found</h1></main>;
  const project = result.data;
  const value = await getValueCase(String(project.opportunity_id));

  return <main className="min-h-screen bg-slate-50 text-slate-950"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><Link href="/" className="font-semibold">STRATOVA</Link><Link href="/consultant/projects" className="text-sm text-slate-500">Projects</Link></div></header><div className="mx-auto max-w-6xl px-6 py-10"><Link href="/consultant/projects" className="text-sm font-medium text-sky-700">← All projects</Link><div className="mt-5 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-sky-700">Delivery & measurement</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">{String(project.name)}</h1><p className="mt-2 text-sm text-slate-500">Opportunity {String(project.opportunity_id).slice(0, 8)}</p></div><span className="rounded-full bg-white px-4 py-2 text-sm font-semibold shadow-sm ring-1 ring-slate-200">{String(project.status)}</span></div><section className="mt-8 grid gap-4 md:grid-cols-3"><Metric label="Contract value" value={project.contract_value == null ? "—" : `${String(project.currency ?? "USD")} ${Number(project.contract_value).toLocaleString()}`} /><Metric label="Start" value={String(project.start_date ?? "—")} /><Metric label="Target end" value={String(project.target_end_date ?? "—")} /></section><section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-semibold">Project lifecycle</h2><p className="mt-2 text-sm leading-6 text-slate-500">Advance the engagement through controlled delivery states. Completed projects remain immutable.</p><ProjectActions projectId={id} status={String(project.status)} /></div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-semibold">Value realization</h2>{value ? <div className="mt-5 grid grid-cols-2 gap-4"><Metric label="Expected benefit" value={`${value.currency} ${value.expectedAnnualBenefit.toLocaleString()}/yr`} /><Metric label="Expected ROI" value={`${value.expectedRoiPercent.toFixed(1)}%`} /><Metric label="Actual benefit" value={value.actualAnnualBenefit == null ? "Not measured" : `${value.currency} ${value.actualAnnualBenefit.toLocaleString()}/yr`} /><Metric label="Actual ROI" value={value.actualRoiPercent == null ? "Not measured" : `${value.actualRoiPercent.toFixed(1)}%`} /></div> : <p className="mt-4 text-sm text-slate-500">No value case has been recorded for this engagement yet.</p>}<Link href={`/api/v1/value/realization?opportunityId=${String(project.opportunity_id)}`} className="mt-5 inline-flex text-sm font-semibold text-sky-700">View realization data →</Link></div></section></div></main>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-lg font-semibold">{value}</p></div>; }
