import type { MisQuestion } from "./types";

export const MIS_QUICKSCAN_QUESTIONS: MisQuestion[] = [
  {
    id: "MIS-Q001",
    dimension: "engineering",
    indicator: "engineering-data-integration",
    question: "How effectively are engineering datasets integrated across planning and technical workflows?",
    weight: 1,
    required: true,
    active: true,
  },
  {
    id: "MIS-Q002",
    dimension: "engineering",
    indicator: "engineering-workflow-digitalization",
    question: "How consistently are engineering workflows supported by digital tools and standardized processes?",
    weight: 1,
    required: true,
    active: true,
  },
  {
    id: "MIS-Q003",
    dimension: "operations",
    indicator: "operational-data-use",
    question: "How effectively is operational data used to support day-to-day decisions?",
    weight: 1,
    required: true,
    active: true,
  },
  {
    id: "MIS-Q004",
    dimension: "operations",
    indicator: "operational-workflow-integration",
    question: "How well are operational workflows connected across teams and systems?",
    weight: 1,
    required: true,
    active: true,
  },
  {
    id: "MIS-Q005",
    dimension: "data",
    indicator: "data-governance",
    question: "How clearly are ownership, quality standards, and governance defined for critical mining data?",
    weight: 1,
    required: true,
    active: true,
  },
  {
    id: "MIS-Q006",
    dimension: "data",
    indicator: "data-accessibility",
    question: "How easily can authorized teams access reliable and current data when decisions are required?",
    weight: 1,
    required: true,
    active: true,
  },
  {
    id: "MIS-Q007",
    dimension: "spatial",
    indicator: "spatial-data-integration",
    question: "How effectively are GIS, survey, drone, and other spatial datasets integrated into operational workflows?",
    weight: 1,
    required: true,
    active: true,
  },
  {
    id: "MIS-Q008",
    dimension: "spatial",
    indicator: "spatial-intelligence",
    question: "To what extent is spatial intelligence used to improve planning, monitoring, and decision making?",
    weight: 1,
    required: true,
    active: true,
  },
  {
    id: "MIS-Q009",
    dimension: "digital",
    indicator: "digital-infrastructure",
    question: "How capable is the current digital infrastructure of supporting integrated mining workflows?",
    weight: 1,
    required: true,
    active: true,
  },
  {
    id: "MIS-Q010",
    dimension: "digital",
    indicator: "systems-integration",
    question: "How effectively do the organization's core technology systems exchange information?",
    weight: 1,
    required: true,
    active: true,
  },
  {
    id: "MIS-Q011",
    dimension: "ai",
    indicator: "ai-readiness",
    question: "How prepared is the organization to deploy AI using reliable data, processes, and appropriate governance?",
    weight: 1,
    required: true,
    active: true,
  },
  {
    id: "MIS-Q012",
    dimension: "ai",
    indicator: "ai-use-cases",
    question: "How systematically does the organization identify, prioritize, and evaluate practical AI use cases?",
    weight: 1,
    required: true,
    active: true,
  },
  {
    id: "MIS-Q013",
    dimension: "value",
    indicator: "value-measurement",
    question: "How consistently are digital initiatives linked to measurable operational or financial outcomes?",
    weight: 1,
    required: true,
    active: true,
  },
  {
    id: "MIS-Q014",
    dimension: "value",
    indicator: "decision-intelligence",
    question: "How effectively does the organization turn data and analysis into timely, actionable decisions?",
    weight: 1,
    required: true,
    active: true,
  },
];
